version: 2.1

orbs:
  gh: circleci/github-cli@2.2.0

jobs:
  build-flutter-linux-arm:
    parameters:
      PROJECT_ID:
        type: string
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium

    steps:
      - checkout

      - run:
          name: Set the build number from current date
          command: |
            echo 'export BUILD_NUMBER=$( date +"%Y%m%d%H" )' >> "$BASH_ENV"
            echo 'export BUILD_NAME=$( git describe --tags )' >> "$BASH_ENV"

      - run:
          name: Install Flutter dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libgtk-3-dev ninja-build bash curl file xz-utils zip clang cmake pkg-config

      - run:
          name: Download the Flutter SDK
          command: |
            git clone https://github.com/flutter/flutter.git -b stable
            echo 'export PATH="$PATH:`pwd`/flutter/bin"' >> "$BASH_ENV"

      - run:
          name: Build Flutter Linux app bundle
          command: |
            flutter config --enable-linux-desktop --no-enable-android
            flutter doctor
            
            # patch Flutter engine
            pushd /tmp
            curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.7.0-stable.tar.xz
            tar -xvf flutter_linux_3.7.0-stable.tar.xz flutter/bin/cache/artifacts/engine/linux-x64/shader_lib
            cp -R flutter/bin/cache/artifacts/engine/linux-x64/shader_lib ~/flutter/bin/cache/artifacts/engine/linux-arm64
            popd
            
            flutter pub get
            flutter build linux --release --target-platform linux-arm64 --build-name $BUILD_NAME --build-number ${BUILD_NUMBER}

      - run:
          name: Compress Flutter build
          command: |
            cp -v web/icons/Icon-maskable-512.png build/linux/arm64/release/bundle/icon.png
            tar -C build/linux/arm64/release/bundle -acvf << parameters.PROJECT_ID >>-linux-arm64-$BUILD_NAME.tar.gz .
            sha256sum << parameters.PROJECT_ID >>-linux-arm64-$BUILD_NAME.tar.gz > << parameters.PROJECT_ID >>-linux-arm64-$BUILD_NAME-sha256sum.txt
            ls
            pwd

      - gh/setup

      - run:
          name: Upload artifacts to GitHub
          command: >
            gh release upload $BUILD_NAME
            << parameters.PROJECT_ID >>-linux-arm64-$BUILD_NAME.tar.gz
            << parameters.PROJECT_ID >>-linux-arm64-$BUILD_NAME-sha256sum.txt

workflows:
  builds-on-arm:
    jobs:
      - build-flutter-linux-arm:
          PROJECT_ID: io.github.carterbox.tofu
          filters:
            tags:
              only: /^[0-9]+.[0-9]+.[0-9]+$/
            branches:
              ignore: /.*/
