version: 2.1

jobs:
  build-flutter-linux-arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    
    steps:
      - checkout

      - run: 
          name: Set the build number from current date
          command: |
            echo 'export BUILD_NUMBER=$( date +"%Y%m%d%H" )' >> "$BASH_ENV"
            echo 'export BUILD_NAME=$( git describe --tags )' >> "$BASH_ENV"

      - run:
          name: Install Flutter dependencies
          command: | 
            sudo apt-get update
            sudo apt-get install -y libgtk-3-dev ninja-build bash curl file xz-utils zip clang cmake pkg-config

      - run:
          name: Download the Flutter SDK
          command: |
            git clone https://github.com/flutter/flutter.git -b 3.3.10
            echo 'export PATH="$PATH:`pwd`/flutter/bin"' >> "$BASH_ENV"

      - run: 
          name: Build Flutter Linux app bundle
          command: |
            flutter config --enable-linux-desktop --no-enable-android
            flutter doctor
            flutter pub get
            flutter build linux --release --target-platform linux-arm64 --build-name $BUILD_NAME --build-number ${BUILD_NUMBER}

      - run:
          name: Compress Flutter build
          command: |
            cp -v linux/flatpak/io.github.carterbox.Tofu.metainfo.xml build/linux/arm64/release/bundle/io.github.carterbox.Tofu.metainfo.xml
            cp -v linux/flatpak/io.github.carterbox.Tofu.desktop build/linux/arm64/release/bundle/io.github.carterbox.Tofu.desktop
            cp -v web/icons/Icon-maskable-512.png build/linux/arm64/release/bundle/icon.png
            tar -C build/linux/arm64/release/bundle -acvf tofu-linux-arm64-${{ env.BUILD_NAME }}.tar.gz .
            sha256sum tofu-linux-arm64-${{ env.BUILD_NAME }}.tar.gz > tofu-linux-arm64-${{ env.BUILD_NAME }}-sha256sum.txt


workflows:
  builds-on-arm:
    jobs:
      - build-flutter-linux-arm
