name: Build Release Appbundles

on:
  workflow_dispatch: # Enable manual run
  push:
    tags:
      # Use pattern matching to only run on version release tags
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  PROJECT_ID: io.github.carterbox.tofu
  BUILD_NAME: ${{ github.ref_name }}

jobs:
  set-the-build-number:
    runs-on: ubuntu-latest
    name: Set the build number from current date
    steps:
      - run: echo BUILD_NUMBER=$( date +"%Y%m%d%H" ) >> $GITHUB_OUTPUT
        id: step1
    outputs:
      build-number: ${{ steps.step1.outputs.BUILD_NUMBER }}

  build-flutter-linux:
    strategy:
      fail-fast: false
      matrix:
        flutter-arch: [x64, arm64]
        include:
          - flutter-arch: x64
            docker-arch: amd64
          - flutter-arch: arm64
            docker-arch: arm64
    needs: set-the-build-number
    name: Build and compress a Linux ${{ matrix.flutter-arch }} app bundle
    runs-on: ubuntu-latest
    container: --platform linux/${{ matrix.docker-arch }} ghcr.io/carterbox/flutter:3.3.10
    steps:
      - name: Build Flutter Linux app bundle
        run: |
          cd /home/flutter
          pwd
          ls
          whoami
          git clone --depth=1 --branch ${{ github.ref }} ${{ github.repositoryUrl }}
          cd tofu

      - name: Build Flutter Linux app bundle
        run: |
          pwd
          flutter config --enable-linux-desktop --no-enable-android --no-enable-web
          flutter doctor
          flutter pub get
          flutter build linux --release --target-platform linux-${{ matrix.flutter-arch }} --build-name ${{ env.BUILD_NAME }} --build-number ${{ needs.set-the-build-number.outputs.build-number }}

      # - name: Compress Flutter build
      #   run: |
      #     cp -v linux/flatpak/io.github.carterbox.Tofu.metainfo.xml build/linux/${{ matrix.flutter-arch }}/release/bundle/io.github.carterbox.Tofu.metainfo.xml
      #     cp -v linux/flatpak/io.github.carterbox.Tofu.desktop build/linux/${{ matrix.flutter-arch }}/release/bundle/io.github.carterbox.Tofu.desktop
      #     cp -v web/icons/Icon-maskable-512.png build/linux/${{ matrix.flutter-arch }}/release/bundle/icon.png
      #     tar -C build/linux/x64/release/bundle -acvf tofu-linux-${{ matrix.flutter-arch }}-${{ env.BUILD_NAME }}.tar.gz .
      #     sha256sum tofu-linux-${{ matrix.flutter-arch }}-${{ env.BUILD_NAME }}.tar.gz > tofu-linux-${{ matrix.flutter-arch }}-${{ env.BUILD_NAME }}-sha256sum.txt

      # - name: Upload files as artifacts to the release
      #   uses: softprops/action-gh-release@v0.1.15
      #   with:
      #     files: |
      #       tofu-linux-${{ matrix.flutter-arch }}-${{ env.BUILD_NAME }}-sha256sum.txt
      #       tofu-linux-${{ matrix.flutter-arch }}-${{ env.BUILD_NAME }}.tar.gz
      #     token: ${{ secrets.LINUX_RELEASE_TOKEN }}

      # - name: Upload app archive for next steps
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: tofu-archive-${{ matrix.flutter-arch }}
      #     path: tofu-linux-${{ matrix.flutter-arch }}-${{ env.BUILD_NAME }}.tar.gz

  build-flutter-google-play:
    needs: set-the-build-number
    name: Build and publish an Android app bundle for Google Play
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Checkout source
        uses: actions/checkout@v3

      # https://docs.github.com/en/actions/security-guides/encrypted-secrets#storing-base64-binary-blobs-as-secrets
      # https://unix.stackexchange.com/a/666142/374857
      - name: Unpack upload signing keys from key store
        env:
          PLAY_UPLOAD_KEY_PROPERTIES: ${{ secrets.PLAY_UPLOAD_KEY_PROPERTIES }}
          PLAY_UPLOAD_KEYSTORE: ${{ secrets.PLAY_UPLOAD_KEYSTORE }}
        run: |
          echo "$PLAY_UPLOAD_KEY_PROPERTIES"==== | fold -w 4 | sed '$ d' | tr -d '\n' | base64 -d > android/key.properties
          echo "$PLAY_UPLOAD_KEYSTORE"==== | fold -w 4 | sed '$ d' | tr -d '\n' | base64 -d > android/app/google-play-keystore.jks

      - name: Build Flutter Android app bundle
        run: |
          flutter pub get
          flutter build appbundle --release --build-name ${{ env.BUILD_NAME }} --build-number ${{ needs.set-the-build-number.outputs.build-number }}

      - uses: r0adkll/upload-google-play@v1.0.19
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: ${{ env.PROJECT_ID }}
          track: alpha
          status: draft
          releaseName: ${{ env.BUILD_NAME }}
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
