name: Build Release Appbundles

on:
  workflow_dispatch: # Enable manual run
  release:
    types: [published]

env:
  project-id: io.github.carterbox.tofu

jobs:
  build-flutter-linux-x86:
    name: Build and compress a Flutter Linux app bundle
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev ninja-build

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Flutter Linux app bundle
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release --target-platform linux-x64 --build-name ${{ github.ref_name }}

      - name: Compress Flutter build
        run: |
          cp -v linux/flatpak/io.github.carterbox.Tofu.metainfo.xml build/linux/x64/release/bundle/io.github.carterbox.Tofu.metainfo.xml
          cp -v linux/flatpak/io.github.carterbox.Tofu.desktop build/linux/x64/release/bundle/io.github.carterbox.Tofu.desktop
          cp -v web/icons/Icon-maskable-512.png build/linux/x64/release/bundle/icon.png
          tar -C build/linux/x64/release/bundle -acvf tofu-linux-x86_64-${{ github.ref_name }}.tar.gz .
          sha256sum tofu-linux-x86_64-${{ github.ref_name }}.tar.gz > tofu-linux-x86_64-${{ github.ref_name }}-sha256sum.txt

      - name: Upload files as artifacts to the release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            tofu-linux-x86_64-${{ github.ref_name }}-sha256sum.txt
            tofu-linux-x86_64-${{ github.ref_name }}.tar.gz
          token: ${{ secrets.LINUX_RELEASE_TOKEN }}

      # - name: Upload app archive for next steps
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: tofu-archive-x86_64
      #     path: tofu-linux-x86_64-${{ github.ref_name }}.tar.gz

  build-flutter-google-play:
    name: Build and publish an Android app bundle for Google Play
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Checkout source
        uses: actions/checkout@v3

      # https://docs.github.com/en/actions/security-guides/encrypted-secrets#storing-base64-binary-blobs-as-secrets
      # https://unix.stackexchange.com/a/666142/374857
      - name: Unpack upload signing keys from key store
        env:
          PLAY_UPLOAD_KEY_PROPERTIES: ${{ secrets.PLAY_UPLOAD_KEY_PROPERTIES }}
          PLAY_UPLOAD_KEYSTORE: ${{ secrets.PLAY_UPLOAD_KEYSTORE }}
        run: |
          echo "$PLAY_UPLOAD_KEY_PROPERTIES"==== | fold -w 4 | sed '$ d' | tr -d '\n' | base64 -d > android/key.properties
          echo "$PLAY_UPLOAD_KEYSTORE"==== | fold -w 4 | sed '$ d' | tr -d '\n' | base64 -d > android/app/google-play-keystore.jks

      - name: Build Flutter Android app bundle
        run: |
          flutter pub get
          flutter build appbundle --release

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: io.github.carterbox.tofu
          track: alpha
          releaseName: ${{ github.ref_name }}
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
